### ISSUE TITLE
AccountLinking preselectedCountry issue

### ISSUE THREAD

**Issue by KestasVenslauskas** [getkevin/kevin-flutter#13]
Hi, first of all thanks for this great flutter package update.
Just started testing it and found a small issue that preselectedCountry gets ignored on Android (iOS not tested yet).
Also probably found a reason for that:

Those 2 lines are incorrect where you assign bank to country value and preselectedCountry as preselectedBank... Sould be a quick fix :)

..
[preselectedBank: model.preselectedCountry?.iso](https://github.com/getkevin/kevin-flutter/blob/aac282126a2f24b5035e7db06159bcee1207e475/packages/kevin_flutter_accounts/kevin_flutter_accounts_platform_interface/lib/src/entity/account/kevin_account_session_configuration_entity.dart#L32)
..
[preselectedCountry: model.preselectedBank](https://github.com/getkevin/kevin-flutter/blob/aac282126a2f24b5035e7db06159bcee1207e475/packages/kevin_flutter_accounts/kevin_flutter_accounts_platform_interface/lib/src/entity/account/kevin_account_session_configuration_entity.dart#L36)

**Comment by antons-zubkovs** [comment]
@KestasVenslauskas thank you for your bug report, the issue has been fixed and update has been published to pub.dev!
