### ISSUE TITLE
skipBankSelection not working on iOS

### ISSUE THREAD

**Issue by KestasVenslauskas** [getkevin/kevin-flutter#32]
Here is my PaymentSessionConfig:
```
 final config = KevinPaymentSessionConfiguration(
      paymentId: paymentState.id,
      paymentType: KevinPaymentType.bank,
      preselectedCountry: KevinCountry.lithuania,
      preselectedBank: selectedBank.id,
      skipBankSelection: true,
      disableCountrySelection: true,
      countryFilter: [
        KevinCountry.lithuania,
      ],
    );
```

This works fine on Android because it shows preselected bank & skips bank selection screen entirely. But on iOS first screen is still bank selection screen which shows preselected bank as current selection.

**Comment by KestasVenslauskas** [comment]
https://user-images.githubusercontent.com/52245569/194487485-9f4fd99a-2d64-483d-9122-c07f74f3fba3.mp4

**Comment by antons-zubkovs** [comment]
@KestasVenslauskas the issue has been found and it will be fixed ASAP, thank you for your report!

**Comment by antons-zubkovs** [comment]
The issue has been fixed and a new version `kevin_flutter_in_app_payments: ^1.0.2` published to pub dev.
